/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames.Administrador;
import Frames.Log;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Franklin
 */
public class RegistrarParadero extends javax.swing.JInternalFrame {
    static Connection conn=null;
    static Statement st=null;
    static ResultSet rs=null;
    static String id;
    DefaultTableModel datostabla=new DefaultTableModel(); 
    /**
     * Creates new form RegistrarParadero
     */
    public RegistrarParadero() {
        initComponents();
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setIconifiable(true);
        String Titulos[]={"ID PARADERO","NOMBRE","DIRECCIÓN","ESTADO","COORDENADAS"};
        datostabla.setColumnIdentifiers(Titulos);
        tbdatos.setModel(datostabla);
        //tbdatos.getColumnModel().getColumn(0).setMaxWidth(0);
        //tbdatos.getColumnModel().getColumn(0).setMinWidth(0);
        //tbdatos.getColumnModel().getColumn(0).setPreferredWidth(0);
        buscar("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCord = new javax.swing.JTextField();
        txtDirec = new javax.swing.JTextField();
        cbxEstado = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbdatos = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar paraderos");

        jLabel1.setText("Registrar paraderos de la empresa de transporte:");

        jLabel2.setText("Ingrese el nombre del paradero:");

        jLabel3.setText("Ingrese la dirrección:");

        jLabel4.setText("Estado del paradero:");

        jLabel5.setText("Coordenadas del paradero:");

        cbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Habilitado", "Deshabilitado", "En reparación" }));

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/guardar.png"))); // NOI18N
        btnAgregar.setText("Registrar");
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });

        tbdatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbdatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbdatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbdatos);

        txtBuscar.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                txtBuscarComponentAdded(evt);
            }
        });
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarKeyPressed(evt);
            }
        });

        jLabel6.setText("Buscar :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(58, 58, 58)
                        .addComponent(txtDirec))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCord)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnAgregar)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(58, 58, 58)
                                .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 15, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDirec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        // TODO add your handling code here:
        try {
            conn=App.ConnectionBd.Enlace(conn);
            st=App.ConnectionBd.sta(st);
            
            String nombpara,direpara,estapara,cordpara,sSQL;
            int transporte=Log.transporte;
            //System.out.println(transporte);
            nombpara=txtNombre.getText();
            direpara=txtDirec.getText();
            estapara=(String)cbxEstado.getSelectedItem();
            cordpara=txtCord.getText();
            
            if (btnAgregar.getText()=="Actualizar"){
                String sql1="update Paradero set nombPara='"+nombpara+"',Transporte_idTran='"+transporte+"',direPara='"+direpara+"',estaPara='"+estapara+"',cordPara='"+cordpara
                        +"' where idPara='"+id+"';";
                Statement st1 = (Statement) conn.createStatement();
                st1.executeUpdate(sql1);
                buscar("");
                limpia();
                conn.close();
            } else {
                if (nombpara.equals("")){
                    JOptionPane.showMessageDialog(null, "Campos sin llenar");
                    txtNombre.grabFocus();
                } else {
                    sSQL="insert into Paradero (Transporte_idTran,nombPara,direPara,estaPara,cordPara)values('"+transporte
                            +"','"+nombpara+"','"+direpara+"','"+estapara+"','"+cordpara+"');";
                    try{
                        Statement st=(Statement) conn.createStatement();
                        st.executeUpdate(sSQL);
                        JOptionPane.showMessageDialog(null, "Registro exitoso");
                    } catch (SQLException ex){
                        JOptionPane.showMessageDialog(null, "Introduzca los datos correctamente");
                    }
                    limpia();
                    buscar("");
                    conn.close();
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al insertar el dato, verifique porfavor.");
        }
    }//GEN-LAST:event_btnAgregarMouseClicked

    private void tbdatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbdatosMouseClicked
        // TODO add your handling code here:
        int fila = -1;
        fila=tbdatos.rowAtPoint(evt.getPoint());
        if(fila > -1){
            id=String.valueOf(tbdatos.getValueAt(fila, 0));
            txtNombre.setText(String.valueOf(tbdatos.getValueAt(fila, 1)));
            txtDirec.setText(String.valueOf(tbdatos.getValueAt(fila, 2)));
            cbxEstado.setSelectedItem(String.valueOf(tbdatos.getValueAt(fila, 3)));
            txtCord.setText(String.valueOf(tbdatos.getValueAt(fila, 4)));
            btnAgregar.setText("Actualizar");
        }
    }//GEN-LAST:event_tbdatosMouseClicked

    private void txtBuscarComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_txtBuscarComponentAdded
        // TODO add your handling code here:
        //buscar(txtBuscar.getText());
    }//GEN-LAST:event_txtBuscarComponentAdded

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
        //buscar(txtBuscar.getText());
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyPressed
        // TODO add your handling code here:
        buscar(txtBuscar.getText());
    }//GEN-LAST:event_txtBuscarKeyPressed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JComboBox<String> cbxEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbdatos;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCord;
    private javax.swing.JTextField txtDirec;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
private void limpia(){
        txtNombre.setText("");
        txtDirec.setText("");
        cbxEstado.setSelectedItem("Habilitado");
        txtCord.setText("");
        txtNombre.grabFocus();
        btnAgregar.setText("Guardar");
    }
private void buscar (String valor){
        try {
            int f,i;
            conn=App.ConnectionBd.Enlace(conn);
            String sql1="Select * from Paradero where estaPara like '%"+valor+"%' or nombPara like '%"+valor+"%'or cordPara like '%"+valor+"%';";
            
            Statement st1=conn.createStatement();
            ResultSet rs1=st1.executeQuery(sql1);
            String datos[]=new String[5];
            f=datostabla.getRowCount();
            if(f>0)
                for(i=0;i<f;i++)
                    datostabla.removeRow(0);
            while(rs1.next()) {
                datos[0]=(String)rs1.getString(1);
                datos[1]=(String)rs1.getString(3);
                datos[2]=(String)rs1.getString(4);
                datos[3]=(String)rs1.getString(5);
                datos[4]=(String)rs1.getString(6);
                datostabla.addRow(datos);
            }
            conn.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al buscar datos, verifique porfavor");
        }
    }
}
