/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames.Empleado;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Franklin
 */
public class IngresarPropietario extends javax.swing.JInternalFrame {
    static Connection conn=null;
    static Statement st=null;
    static ResultSet rs=null;
    DefaultTableModel datostabla=new DefaultTableModel();  
    /**
     * Creates new form RegistrarPropietario
     */
    public IngresarPropietario() {
        initComponents();
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setIconifiable(true);
        
        String Titulos[]={"DNI","NOMBRE","APELLIDO","TELEFONO","DOMICILIO","CBANCO","RUC"};
        datostabla.setColumnIdentifiers(Titulos);
        tbdatos.setModel(datostabla);
        //tbdatos.getColumnModel().getColumn(0).setMaxWidth(0);
        //tbdatos.getColumnModel().getColumn(0).setMinWidth(0);
        //tbdatos.getColumnModel().getColumn(0).setPreferredWidth(0);
        buscar("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblDni = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblCel = new javax.swing.JLabel();
        lblDomicilio = new javax.swing.JLabel();
        lblBanco = new javax.swing.JLabel();
        lblRuc = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtCel = new javax.swing.JTextField();
        txtDomicilio = new javax.swing.JTextField();
        txtBanco = new javax.swing.JTextField();
        txtRuc = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbdatos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar propietario");

        lblTitulo.setText("Registrar propietario:");

        lblDni.setText("Ingrese DNI:");

        lblNombre.setText("Nombres:");

        lblApellido.setText("Apellidos:");

        lblCel.setText("Cel/telf:");

        lblDomicilio.setText("Domicilio:");

        lblBanco.setText("Cuenta de banco:");

        lblRuc.setText("RUC:");

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/agregar.png"))); // NOI18N
        btnAgregar.setText("Ingresar vehiculo");
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });

        jLabel1.setText("Buscar :");

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarKeyPressed(evt);
            }
        });

        tbdatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbdatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbdatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbdatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblDni)
                        .addGap(42, 42, 42)
                        .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblBanco)
                        .addGap(18, 18, 18)
                        .addComponent(txtBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblNombre)
                        .addGap(58, 58, 58)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblRuc)
                        .addGap(79, 79, 79)
                        .addComponent(txtRuc, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblApellido)
                        .addGap(58, 58, 58)
                        .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCel)
                            .addComponent(lblDomicilio))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCel, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(92, 92, 92)
                        .addComponent(btnAgregar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel1)
                        .addGap(10, 10, 10)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDni)
                            .addComponent(lblBanco))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addComponent(lblRuc))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblApellido))
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblCel)
                        .addGap(24, 24, 24)
                        .addComponent(lblDomicilio))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(btnAgregar)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbdatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbdatosMouseClicked
        // TODO add your handling code here:
        int fila = -1;
        fila=tbdatos.rowAtPoint(evt.getPoint());
        if(fila > -1){
            txtDni.setText(String.valueOf(tbdatos.getValueAt(fila, 0)));
            txtNombre.setText(String.valueOf(tbdatos.getValueAt(fila, 1)));
            txtApellido.setText(String.valueOf(tbdatos.getValueAt(fila, 2)));
            txtCel.setText(String.valueOf(tbdatos.getValueAt(fila, 3)));
            txtDomicilio.setText(String.valueOf(tbdatos.getValueAt(fila, 4)));
            txtBanco.setText(String.valueOf(tbdatos.getValueAt(fila, 5)));
            txtRuc.setText(String.valueOf(tbdatos.getValueAt(fila, 6)));
            btnAgregar.setText("Actualizar");
        }
    }//GEN-LAST:event_tbdatosMouseClicked

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        // TODO add your handling code here:
        try {
            conn=App.ConnectionBd.Enlace(conn);
            st=App.ConnectionBd.sta(st);
            String nombre,apellido,telefono,domicilio,banco,ruc,sSQL;
            int dni;
            nombre=txtNombre.getText();
            apellido=txtApellido.getText();
            telefono=txtCel.getText();
            domicilio=txtDomicilio.getText();
            ruc=txtRuc.getText();
            banco=txtBanco.getText();
            dni=Integer.parseInt(txtDni.getText());
            
            if (btnAgregar.getText()=="Actualizar"){
                String sql1="update Propietario set dniProp='"+dni+"',nombProp='"+nombre+"',apelProp='"+apellido+"',"
                        + "telfProp='"+telefono+"',direProp='"+domicilio+"',cuenBancProp='"+banco+"',rucProp='"+ruc+"' "
                        + "where dniProp='"+dni+"';";
                Statement st1=(Statement) conn.createStatement();
                st1.executeUpdate(sql1);
                buscar("");
                limpia();
                conn.close();
            } else {
                if (nombre.equals("")){
                    JOptionPane.showMessageDialog(null, "Campos sin llenar");
                    txtNombre.grabFocus();
                } else {
                    sSQL="insert Propietario values ('"+dni+"','"+nombre+"','"+apellido+"','"+telefono+"','"+domicilio+"','"+banco+"','"+ruc+"');";
                    try{
                        Statement st=(Statement) conn.createStatement();
                        st.executeUpdate(sSQL);
                        JOptionPane.showMessageDialog(null, "Registro exitoso");
                    } catch (SQLException ex){
                        JOptionPane.showMessageDialog(null, "Introduzca los datos correctamente");
                    }
                    
                    limpia();
                    buscar("");
                    conn.close();
                }
            
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al insertar el dato, verifique porfavor.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Introduzca los datos correctamente");
        }
    }//GEN-LAST:event_btnAgregarMouseClicked

    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyPressed
        // TODO add your handling code here:
        buscar(txtBuscar.getText());
    }//GEN-LAST:event_txtBuscarKeyPressed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblBanco;
    private javax.swing.JLabel lblCel;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblDomicilio;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRuc;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tbdatos;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtBanco;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCel;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtDomicilio;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRuc;
    // End of variables declaration//GEN-END:variables
    private void limpia(){
        txtDni.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtCel.setText("");
        txtDomicilio.setText("");
        txtBanco.setText("");
        txtRuc.setText("");    
        txtDni.grabFocus();
        btnAgregar.setText("Guardar");
    }
    private void buscar (String valor){
        try {
            int f,i;
            conn=App.ConnectionBd.Enlace(conn);
            String sql1="Select * from Propietario where dniProp like '%"+valor+"%' or nombProp like '%"+valor+"%';";
            
            Statement st1=conn.createStatement();
            ResultSet rs1=st1.executeQuery(sql1);
            String datos[]=new String[7];
            f=datostabla.getRowCount();
            if(f>0)
                for(i=0;i<f;i++)
                    datostabla.removeRow(0);
            while(rs1.next()) {
                datos[0]=(String)rs1.getString(1);
                datos[1]=(String)rs1.getString(2);
                datos[2]=(String)rs1.getString(3);
                datos[3]=(String)rs1.getString(4);
                datos[4]=(String)rs1.getString(5);
                datos[5]=(String)rs1.getString(6);
                datos[6]=(String)rs1.getString(7);
                datostabla.addRow(datos);
            }
            conn.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al buscar datos, verifique porfavor");
        }
    }
}
