/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames.Empleado;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Franklin
 */
public class IngresarOperarios extends javax.swing.JInternalFrame {
    static Connection conn=null;
    static Statement st=null;
    static ResultSet rs=null;
    DefaultTableModel datostabla=new DefaultTableModel();  

    /**
     * Creates new form IngresarOperarios
     */
    public IngresarOperarios() {
        initComponents();
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setIconifiable(true);
        lblVehiculo.setVisible(false);
        txtVehiculo.setVisible(false);
        lblLicencia.setVisible(false);
        txtLicencia.setVisible(false);
        lblAyudante.setVisible(false);
        txtAyudante.setVisible(false);
        String Titulos[]={"DNI","NOMBRE","APELLIDO","TELEF","EMAIL","CBANCO","TRANSPORTE","LICENCIA","VEHICULO","AYUDANTE"};
        datostabla.setColumnIdentifiers(Titulos);
        tbdatos.setModel(datostabla);
        //tbdatos.getColumnModel().getColumn(0).setMaxWidth(0);
        //tbdatos.getColumnModel().getColumn(0).setMinWidth(0);
        //tbdatos.getColumnModel().getColumn(0).setPreferredWidth(0);
        buscar("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEmail = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtLicencia = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        lblDni = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        lblApellido = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        lblContraseña = new javax.swing.JLabel();
        lblCel = new javax.swing.JLabel();
        lblOperario = new javax.swing.JLabel();
        lblTipoOperario = new javax.swing.JLabel();
        cbxTipoOperario = new javax.swing.JComboBox<>();
        lblLicencia = new javax.swing.JLabel();
        txtTransporte = new javax.swing.JTextField();
        lblVehiculo = new javax.swing.JLabel();
        lblTransporte = new javax.swing.JLabel();
        txtVehiculo = new javax.swing.JTextField();
        txtBanco = new javax.swing.JTextField();
        txtCel = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbdatos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        lblAyudante = new javax.swing.JLabel();
        txtAyudante = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ingresar operarios");

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/adduser.png"))); // NOI18N
        btnAgregar.setText("Agregar operario");
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });

        lblDni.setText("Ingrse DNI:");

        lblNombre.setText("Nombre:");

        lblApellido.setText("Apellido:");

        lblEmail.setText("Email:");

        lblContraseña.setText("Número de cel:");

        lblCel.setText("Cuenta de banco:");

        lblOperario.setText("Ingrese operario:");

        lblTipoOperario.setText("Tipo de operario:");

        cbxTipoOperario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ayudante", "Conductor" }));
        cbxTipoOperario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxTipoOperarioItemStateChanged(evt);
            }
        });
        cbxTipoOperario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoOperarioActionPerformed(evt);
            }
        });

        lblLicencia.setText("N° licencia:");

        lblVehiculo.setText("Placa Vehiculo:");

        lblTransporte.setText("ID Transporte:");

        tbdatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbdatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbdatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbdatos);

        jLabel1.setText("Buscar :");

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarKeyPressed(evt);
            }
        });

        lblAyudante.setText("DNI Ayudante:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblOperario))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblTipoOperario)
                        .addGap(10, 10, 10)
                        .addComponent(cbxTipoOperario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblDni)
                        .addGap(35, 35, 35)
                        .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(lblCel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblEmail)
                        .addGap(63, 63, 63)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(lblLicencia)
                        .addGap(72, 72, 72)
                        .addComponent(txtLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblContraseña)
                        .addGap(20, 20, 20)
                        .addComponent(txtCel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(lblAyudante)
                        .addGap(53, 53, 53)
                        .addComponent(txtAyudante, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(412, 412, 412)
                        .addComponent(btnAgregar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblApellido)
                                .addGap(50, 50, 50)
                                .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(lblVehiculo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNombre)
                                .addGap(50, 50, 50)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(lblTransporte)))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblOperario)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblTipoOperario))
                    .addComponent(cbxTipoOperario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblDni))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(lblCel)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(lblNombre))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTransporte)
                                    .addComponent(txtTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(lblApellido))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lblVehiculo))
                            .addComponent(txtVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(lblEmail))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lblLicencia))
                            .addComponent(txtLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAyudante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblContraseña)
                                    .addComponent(lblAyudante))))
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregar)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel1))
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxTipoOperarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoOperarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTipoOperarioActionPerformed

    private void tbdatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbdatosMouseClicked
        // TODO add your handling code here:
        int fila = -1;
        fila=tbdatos.rowAtPoint(evt.getPoint());
        if(fila > -1){
            //cbxTipoOperario.setSelectedItem(String.valueOf(tbdatos.getValueAt(fila, 0)));
            txtDni.setText(String.valueOf(tbdatos.getValueAt(fila, 0)));
            txtNombre.setText(String.valueOf(tbdatos.getValueAt(fila, 1)));
            txtApellido.setText(String.valueOf(tbdatos.getValueAt(fila, 2)));
            txtCel.setText(String.valueOf(tbdatos.getValueAt(fila, 3)));
            txtEmail.setText(String.valueOf(tbdatos.getValueAt(fila, 4)));
            txtBanco.setText(String.valueOf(tbdatos.getValueAt(fila, 5)));
            txtTransporte.setText(String.valueOf(tbdatos.getValueAt(fila, 6)));
            txtLicencia.setText(String.valueOf(tbdatos.getValueAt(fila, 7))); 
            txtVehiculo.setText(String.valueOf(tbdatos.getValueAt(fila, 8)));
            txtAyudante.setText(String.valueOf(tbdatos.getValueAt(fila, 9)));
            btnAgregar.setText("Actualizar");
        }
    }//GEN-LAST:event_tbdatosMouseClicked

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        // TODO add your handling code here:
        try {
            conn=App.ConnectionBd.Enlace(conn);
            st=App.ConnectionBd.sta(st);
            String tipo,nombre,apellido,telefono,correo,banco,licencia,vehiculo,dniayudante,sSQL;
            int dni,transporte;
            tipo=String.valueOf(cbxTipoOperario.getSelectedItem());
            nombre=txtNombre.getText();
            apellido=txtApellido.getText();
            correo=txtEmail.getText();
            licencia=txtLicencia.getText();
            vehiculo=txtVehiculo.getText();
            banco=txtBanco.getText();
            telefono=txtCel.getText();
            dni=Integer.parseInt(txtDni.getText());
            transporte=Integer.parseInt(txtTransporte.getText());
            dniayudante=txtAyudante.getText();

            if (btnAgregar.getText()=="Actualizar"){
                if(cbxTipoOperario.getSelectedItem()=="Ayudante"){
                    String sql1="update Ayudante set dniAyudante='"+dni+"',nomAyud='"+nombre+"',apelAyud='"
                            +apellido+"',telfAyud='"+telefono+"',coreAyud='"+correo+"',cuentaBancAyud='"+banco+
                            "',Transporte_idTran='"+transporte+"' where dniAyudante='"+dni+"';";
                    Statement st1=(Statement) conn.createStatement();
                    st1.executeUpdate(sql1);
                    buscar("");
                    limpia();
                    conn.close();
                } else {
                    String sql1="update Conductor set dniCond='"+dni+"',nomCond='"+nombre+"',apelCond='"+apellido+
                            "',telfCond='"+telefono+"',coreCond='"+correo+"',numeLiceCond='"+licencia+"',cuenBancCond='"+banco+"',Transporte_idTran='"
                            +transporte+"',numeLiceCond='"+licencia+"',Vehiculo_placVehi='"+vehiculo+"',Ayudante_dniAyudante='"
                            +dniayudante+"' where dniCond='"+dni+"';";
                    Statement st1=(Statement) conn.createStatement();
                    st1.executeUpdate(sql1);
                    buscar("");
                    limpia();
                    conn.close();
                }

            } else {
                if (nombre.equals("")){
                    JOptionPane.showMessageDialog(null, "Campos sin llenar");
                    txtNombre.grabFocus();
                } else {
                    if (cbxTipoOperario.getSelectedItem()=="Ayudante") {
                        sSQL="insert Ayudante values ('"+dni+"','"+nombre+"','"+apellido+"','"+telefono+"','"+correo+"','"+banco+"','"+transporte+"');";
                    } else {
                        sSQL="insert Conductor values ('"+dni+"','"+nombre+"','"+apellido+"','"+telefono+"','"+correo+"','"+banco+"','"+transporte+"','"+licencia+"','"+vehiculo+"','"+dniayudante+"');";
                    }
                    try{
                        Statement st=(Statement) conn.createStatement();
                        st.executeUpdate(sSQL);
                        JOptionPane.showMessageDialog(null, "Registro exitoso");
                    } catch (SQLException ex){
                        JOptionPane.showMessageDialog(null, ex);
                    }
                    
                    limpia();
                    buscar("");
                    conn.close();
                }

            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al insertar el dato, verifique porfavor.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Introduzca los datos correctamente");
        }
    }//GEN-LAST:event_btnAgregarMouseClicked

    private void cbxTipoOperarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxTipoOperarioItemStateChanged
        // TODO add your handling code here:
        String tipo = "";
        tipo = (String) cbxTipoOperario.getSelectedItem();
        if (tipo.equals("Ayudante")) {
            lblVehiculo.setVisible(false);
            txtVehiculo.setVisible(false);
            lblLicencia.setVisible(false);
            txtLicencia.setVisible(false);
            lblAyudante.setVisible(false);
            txtAyudante.setVisible(false);
            //limpia();
            txtNombre.setText("");
            txtApellido.setText("");
            txtEmail.setText("");
            txtLicencia.setText("");
            txtVehiculo.setText("");
            txtBanco.setText("");
            txtDni.setText("");
            txtCel.setText("");
            txtTransporte.setText("");
            txtAyudante.setText("");
            btnAgregar.setText("Guardar");
            buscar("");
        } else {
            lblVehiculo.setVisible(true);
            txtVehiculo.setVisible(true);
            lblLicencia.setVisible(true);
            txtLicencia.setVisible(true);
            lblAyudante.setVisible(true);
            txtAyudante.setVisible(true);
            //limpia();
            txtNombre.setText("");
            txtApellido.setText("");
            txtEmail.setText("");
            txtLicencia.setText("");
            txtVehiculo.setText("");
            txtBanco.setText("");
            txtDni.setText("");
            txtCel.setText("");
            txtTransporte.setText("");
            txtAyudante.setText("");
            btnAgregar.setText("Guardar");
            buscar("");
        }
    }//GEN-LAST:event_cbxTipoOperarioItemStateChanged

    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyPressed
        // TODO add your handling code here:
        buscar(txtBuscar.getText());
    }//GEN-LAST:event_txtBuscarKeyPressed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JComboBox<String> cbxTipoOperario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblAyudante;
    private javax.swing.JLabel lblCel;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblLicencia;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblOperario;
    private javax.swing.JLabel lblTipoOperario;
    private javax.swing.JLabel lblTransporte;
    private javax.swing.JLabel lblVehiculo;
    private javax.swing.JTable tbdatos;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtAyudante;
    private javax.swing.JTextField txtBanco;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCel;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLicencia;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTransporte;
    private javax.swing.JTextField txtVehiculo;
    // End of variables declaration//GEN-END:variables
    private void limpia(){
        txtNombre.setText("");
        txtApellido.setText("");
        txtEmail.setText("");
        txtLicencia.setText("");
        txtVehiculo.setText("");
        txtBanco.setText("");
        txtDni.setText("");
        txtCel.setText("");
        txtTransporte.setText("");
        txtAyudante.setText("");
        txtNombre.grabFocus();
        btnAgregar.setText("Guardar");
    }
    private void buscar (String valor){
        try {
            int f,i;
            conn=App.ConnectionBd.Enlace(conn);
            String sql1;
            if (cbxTipoOperario.getSelectedItem()=="Ayudante") {
                sql1 = "Select * from Ayudante where dniAyudante like '%"+valor+"%' or nomAyud like '%"+valor+"%';";
            } else {
                sql1 = "Select * from Conductor where dniCond like '%"+valor+"%' or nomCond like '%"+valor+"%';";
            }
            
            Statement st1=conn.createStatement();
            ResultSet rs1=st1.executeQuery(sql1);
            String datos[]=new String[10];
            f=datostabla.getRowCount();
            if(f>0)
                for(i=0;i<f;i++)
                    datostabla.removeRow(0);
            while(rs1.next()) {
                if (cbxTipoOperario.getSelectedItem()=="Ayudante"){
                    datos[0]=(String)rs1.getString(1);
                    datos[1]=(String)rs1.getString(2);
                    datos[2]=(String)rs1.getString(3);
                    datos[3]=(String)rs1.getString(4);
                    datos[4]=(String)rs1.getString(5);
                    datos[5]=(String)rs1.getString(6);
                    datos[6]=(String)rs1.getString(7);
                    datostabla.addRow(datos);
                } else {
                    datos[0]=(String)rs1.getString(1);
                    datos[1]=(String)rs1.getString(2);
                    datos[2]=(String)rs1.getString(3);
                    datos[3]=(String)rs1.getString(4);
                    datos[4]=(String)rs1.getString(5);
                    datos[5]=(String)rs1.getString(6);
                    datos[6]=(String)rs1.getString(7);
                    datos[7]=(String)rs1.getString(8);
                    datos[8]=(String)rs1.getString(9);
                    datos[9]=(String)rs1.getString(10);
                    datostabla.addRow(datos);
                }
                
            }
            conn.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al buscar datos, verifique porfavor");
        }
    }
}
