/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames.Empleado;

import Frames.Cuenta;
import Frames.Informacion;
import Frames.Log;
import com.jgoodies.looks.plastic.Plastic3DLookAndFeel;
import com.jgoodies.looks.plastic.theme.DarkStar;
import java.awt.Component;
import java.awt.Dimension;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Graphics;
import java.awt.Insets;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URL;
import java.text.DateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.border.Border;

/**
 *
 * @author Franklin
 */
public class MainFormEmpleado extends javax.swing.JFrame implements Runnable{
    Thread h1;
    String hora,minutos,segundos,ampm;
    Calendar calendario;
    String urls="/Icons/fondoEmpresa.png";
    @Override
    public void run(){
        Thread ct=Thread.currentThread();
        while(ct == h1){
            calcula();
            lblHora.setText(hora+ ":" + minutos+ ":" +segundos+" "+ampm);
            try {
                Thread.sleep(1000);
            } catch(InterruptedException e){}
        }
    }
    /**
     * Creates new form MainForm
     */
    public MainFormEmpleado() {
        initComponents();
        h1 = new Thread(this);
        h1.start();
        fecha();
        this.setExtendedState(MAXIMIZED_BOTH);
        setIconImage(new ImageIcon(getClass().getResource("/Icons/icon.png")).getImage());
        urls="/Icons/fondoEmpresa.png";
        jpaneEscritorio.setBorder(new ImagenFondo(urls));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpaneMenu = new javax.swing.JPanel();
        lblBienvenido = new javax.swing.JLabel();
        btnOperarios = new javax.swing.JButton();
        btnVehiculos = new javax.swing.JButton();
        btnControl = new javax.swing.JButton();
        lblFotoUser = new javax.swing.JLabel();
        btnIngreso = new javax.swing.JButton();
        btnPago = new javax.swing.JButton();
        btnPropietario = new javax.swing.JButton();
        lblComentario = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        jpaneEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuInicio = new javax.swing.JMenu();
        menuConf = new javax.swing.JMenu();
        menuCuenta = new javax.swing.JMenuItem();
        menuFondo = new javax.swing.JMenu();
        menuFondo1 = new javax.swing.JMenuItem();
        menuFondo2 = new javax.swing.JMenuItem();
        menuFondo3 = new javax.swing.JMenuItem();
        menuFondo4 = new javax.swing.JMenuItem();
        menuFondo5 = new javax.swing.JMenuItem();
        menuFondo6 = new javax.swing.JMenuItem();
        menuDiseño = new javax.swing.JMenu();
        menuDiseño1 = new javax.swing.JMenuItem();
        menuDiseño2 = new javax.swing.JMenuItem();
        menuDiseño3 = new javax.swing.JMenuItem();
        menuDiseño4 = new javax.swing.JMenuItem();
        menuInfo = new javax.swing.JMenu();
        menuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Empleado - Sistema de transporte integrado: La solución para el Perú");

        jpaneMenu.setBackground(new java.awt.Color(204, 204, 204));

        lblBienvenido.setText("Bienvenido:");

        btnOperarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/operarios.png"))); // NOI18N
        btnOperarios.setText("Ingresar operarios");
        btnOperarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOperariosActionPerformed(evt);
            }
        });

        btnVehiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/vehiculos.png"))); // NOI18N
        btnVehiculos.setText("Ingresar vehiculos");
        btnVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehiculosActionPerformed(evt);
            }
        });

        btnControl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ruta.png"))); // NOI18N
        btnControl.setText("Control de ruta");
        btnControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControlActionPerformed(evt);
            }
        });

        lblFotoUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/user.png"))); // NOI18N

        btnIngreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ingreso.png"))); // NOI18N
        btnIngreso.setText("Registrar ingreso");
        btnIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresoActionPerformed(evt);
            }
        });

        btnPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/pago.png"))); // NOI18N
        btnPago.setText("Registrar pago");
        btnPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagoActionPerformed(evt);
            }
        });

        btnPropietario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/propietario.png"))); // NOI18N
        btnPropietario.setText("Ingresar propietario");
        btnPropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPropietarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpaneMenuLayout = new javax.swing.GroupLayout(jpaneMenu);
        jpaneMenu.setLayout(jpaneMenuLayout);
        jpaneMenuLayout.setHorizontalGroup(
            jpaneMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaneMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpaneMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVehiculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpaneMenuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblFotoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnOperarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpaneMenuLayout.createSequentialGroup()
                        .addComponent(lblBienvenido)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnPropietario, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpaneMenuLayout.setVerticalGroup(
            jpaneMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaneMenuLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblFotoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBienvenido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPropietario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVehiculos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOperarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnControl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIngreso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPago)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        lblComentario.setText("@stransintgr.com");

        lblFecha.setText("jLabel1");

        lblHora.setText("jLabel1");

        javax.swing.GroupLayout jpaneEscritorioLayout = new javax.swing.GroupLayout(jpaneEscritorio);
        jpaneEscritorio.setLayout(jpaneEscritorioLayout);
        jpaneEscritorioLayout.setHorizontalGroup(
            jpaneEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpaneEscritorioLayout.setVerticalGroup(
            jpaneEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        menuInicio.setText("Inicio");
        jMenuBar1.add(menuInicio);

        menuConf.setText("Configuración");

        menuCuenta.setText("Cuenta");
        menuCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCuentaMouseClicked(evt);
            }
        });
        menuCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCuentaActionPerformed(evt);
            }
        });
        menuConf.add(menuCuenta);

        menuFondo.setText("Fondo");

        menuFondo1.setText("Fondo 1");
        menuFondo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFondo1ActionPerformed(evt);
            }
        });
        menuFondo.add(menuFondo1);

        menuFondo2.setText("Fondo 2");
        menuFondo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFondo2ActionPerformed(evt);
            }
        });
        menuFondo.add(menuFondo2);

        menuFondo3.setText("Fondo 3");
        menuFondo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFondo3ActionPerformed(evt);
            }
        });
        menuFondo.add(menuFondo3);

        menuFondo4.setText("Fondo 4");
        menuFondo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFondo4ActionPerformed(evt);
            }
        });
        menuFondo.add(menuFondo4);

        menuFondo5.setText("Fondo 5");
        menuFondo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFondo5ActionPerformed(evt);
            }
        });
        menuFondo.add(menuFondo5);

        menuFondo6.setText("Fondo 6");
        menuFondo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFondo6ActionPerformed(evt);
            }
        });
        menuFondo.add(menuFondo6);

        menuConf.add(menuFondo);

        menuDiseño.setText("Diseño");

        menuDiseño1.setText("Diseño 1");
        menuDiseño1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDiseño1ActionPerformed(evt);
            }
        });
        menuDiseño.add(menuDiseño1);

        menuDiseño2.setText("Diseño 2");
        menuDiseño2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDiseño2ActionPerformed(evt);
            }
        });
        menuDiseño.add(menuDiseño2);

        menuDiseño3.setText("Diseño 3");
        menuDiseño3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDiseño3ActionPerformed(evt);
            }
        });
        menuDiseño.add(menuDiseño3);

        menuDiseño4.setText("Diseño 4");
        menuDiseño4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDiseño4ActionPerformed(evt);
            }
        });
        menuDiseño.add(menuDiseño4);

        menuConf.add(menuDiseño);

        jMenuBar1.add(menuConf);

        menuInfo.setText("Información");
        menuInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuInfoMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuInfo);

        menuSalir.setText("Salir");
        menuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSalirMouseClicked(evt);
            }
        });
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpaneMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblHora)
                        .addGap(33, 33, 33)
                        .addComponent(lblFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, Short.MAX_VALUE)
                        .addComponent(lblUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(lblComentario)
                        .addGap(4, 4, 4))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpaneEscritorio))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpaneMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpaneEscritorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHora)
                    .addComponent(lblFecha)
                    .addComponent(lblComentario)
                    .addComponent(lblUsuario)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOperariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperariosActionPerformed
        // TODO add your handling code here:
        IngresarOperarios o=new IngresarOperarios();
        jpaneEscritorio.add(o);
        Dimension pantalla=Toolkit.getDefaultToolkit().getScreenSize();
        Dimension ventana=o.getSize();
        o.setLocation((pantalla.width-ventana.width)/3, (pantalla.height-ventana.height)/5);
        o.setVisible(true);
    }//GEN-LAST:event_btnOperariosActionPerformed

    private void btnPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagoActionPerformed
        // TODO add your handling code here:
        RegistrarPago p=new RegistrarPago();
        jpaneEscritorio.add(p);
        Dimension pantalla=Toolkit.getDefaultToolkit().getScreenSize();
        Dimension ventana=p.getSize();
        p.setLocation((pantalla.width-ventana.width)/3, (pantalla.height-ventana.height)/5);
        p.setVisible(true);
    }//GEN-LAST:event_btnPagoActionPerformed

    private void btnVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehiculosActionPerformed
        // TODO add your handling code here:
        IngresarVehiculos v=new IngresarVehiculos();
        jpaneEscritorio.add(v);
        Dimension pantalla=Toolkit.getDefaultToolkit().getScreenSize();
        Dimension ventana=v.getSize();
        v.setLocation((pantalla.width-ventana.width)/3, (pantalla.height-ventana.height)/5);
        v.setVisible(true);
    }//GEN-LAST:event_btnVehiculosActionPerformed

    private void btnControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControlActionPerformed
        // TODO add your handling code here:
        ControlRuta c=new ControlRuta();
        jpaneEscritorio.add(c);
        Dimension pantalla=Toolkit.getDefaultToolkit().getScreenSize();
        Dimension ventana=c.getSize();
        c.setLocation((pantalla.width-ventana.width)/3, (pantalla.height-ventana.height)/5);
        c.setVisible(true);
    }//GEN-LAST:event_btnControlActionPerformed

    private void btnIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoActionPerformed
        // TODO add your handling code here:
        RegistrarIngreso i=new RegistrarIngreso();
        jpaneEscritorio.add(i);
        Dimension pantalla=Toolkit.getDefaultToolkit().getScreenSize();
        Dimension ventana=i.getSize();
        i.setLocation((pantalla.width-ventana.width)/3, (pantalla.height-ventana.height)/5);
        i.setVisible(true);
    }//GEN-LAST:event_btnIngresoActionPerformed

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuSalirActionPerformed

    private void menuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSalirMouseClicked
        // TODO add your handling code here:
        Log login=new Log();
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_menuSalirMouseClicked

    private void menuInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuInfoMouseClicked
        // TODO add your handling code here:
        Informacion i=new Informacion();
        jpaneEscritorio.add(i);
        Dimension pantalla=Toolkit.getDefaultToolkit().getScreenSize();
        Dimension ventana=i.getSize();
        i.setLocation((pantalla.width-ventana.width)/3, (pantalla.height-ventana.height)/5);
        i.setVisible(true); 
    }//GEN-LAST:event_menuInfoMouseClicked

    private void menuCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCuentaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCuentaMouseClicked

    private void menuCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCuentaActionPerformed
        // TODO add your handling code here:
        Cuenta c=new Cuenta();
        jpaneEscritorio.add(c);
        Dimension pantalla=Toolkit.getDefaultToolkit().getScreenSize();
        Dimension ventana=c.getSize();
        c.setLocation((pantalla.width-ventana.width)/3, (pantalla.height-ventana.height)/5);
        c.setVisible(true); 
    }//GEN-LAST:event_menuCuentaActionPerformed

    private void menuFondo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFondo1ActionPerformed
        // TODO add your handling code here:
        urls="/Icons/fondo.png";
        jpaneEscritorio.setBorder(new ImagenFondo(urls));
    }//GEN-LAST:event_menuFondo1ActionPerformed

    private void menuFondo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFondo2ActionPerformed
        // TODO add your handling code here:
        urls="/Icons/fondo2.jpeg";
        jpaneEscritorio.setBorder(new ImagenFondo(urls));
    }//GEN-LAST:event_menuFondo2ActionPerformed

    private void menuFondo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFondo3ActionPerformed
        // TODO add your handling code here:
        urls="/Icons/fondo3.jpeg";
        jpaneEscritorio.setBorder(new ImagenFondo(urls));
    }//GEN-LAST:event_menuFondo3ActionPerformed

    private void menuFondo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFondo4ActionPerformed
        // TODO add your handling code here:
        urls="/Icons/fondo4.jpg";
        jpaneEscritorio.setBorder(new ImagenFondo(urls));
    }//GEN-LAST:event_menuFondo4ActionPerformed

    private void menuFondo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFondo5ActionPerformed
        // TODO add your handling code here:
        urls="/Icons/fondo5.jpg";
        jpaneEscritorio.setBorder(new ImagenFondo(urls));
    }//GEN-LAST:event_menuFondo5ActionPerformed

    private void menuFondo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFondo6ActionPerformed
        // TODO add your handling code here:
        urls="/Icons/fondoEmpresa.png";
        jpaneEscritorio.setBorder(new ImagenFondo(urls));
    }//GEN-LAST:event_menuFondo6ActionPerformed

    private void menuDiseño1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDiseño1ActionPerformed
        // TODO add your handling code here:
        try {
            Plastic3DLookAndFeel.setPlasticTheme(new DarkStar());
            UIManager.setLookAndFeel("com.jgoodies.looks.plastic.PlasticLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null,"Vuelva a iniciar sesión para visualizar los cambios.");
    }//GEN-LAST:event_menuDiseño1ActionPerformed

    private void menuDiseño2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDiseño2ActionPerformed
        // TODO add your handling code here:
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFormEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFormEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFormEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFormEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null,"Vuelva a iniciar sesión para visualizar los cambios.");
    }//GEN-LAST:event_menuDiseño2ActionPerformed

    private void menuDiseño3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDiseño3ActionPerformed
        // TODO add your handling code here:
        try {
            UIManager.setLookAndFeel("UpperEssential.UpperEssentialLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null,"Vuelva a iniciar sesión para visualizar los cambios.");
    }//GEN-LAST:event_menuDiseño3ActionPerformed

    private void menuDiseño4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDiseño4ActionPerformed
        // TODO add your handling code here:
        try {
            UIManager.setLookAndFeel("com.birosoft.liquid.LiquidLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null,"Vuelva a iniciar sesión para visualizar los cambios.");
    }//GEN-LAST:event_menuDiseño4ActionPerformed

    private void btnPropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPropietarioActionPerformed
        // TODO add your handling code here:
        IngresarPropietario p=new IngresarPropietario();
        jpaneEscritorio.add(p);
        Dimension pantalla=Toolkit.getDefaultToolkit().getScreenSize();
        Dimension ventana=p.getSize();
        p.setLocation((pantalla.width-ventana.width)/3, (pantalla.height-ventana.height)/5);
        p.setVisible(true);
       
    }//GEN-LAST:event_btnPropietarioActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFormEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFormEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFormEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFormEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        try {
            //Plantillas
            //UIManager.setLookAndFeel("com.sun.java.swing.plaf.metal.nimbus.NimbusLookAndFeel");
            //UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
            //UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.Windows.LookAndFeel");
            UIManager.setLookAndFeel("com.birosoft.liquid.LiquidLookAndFeel");
            //UIManager.setLookAndFeel("UpperEssential.UpperEssentialLookAndFeel");
            //UIManager.setLookAndFeel("com.jgoodies.looks.windows.WindowsLookAndFeel");
            //Plastic3DLookAndFeel.setPlasticTheme(new DarkStar());
            //UIManager.setLookAndFeel("com.jgoodies.looks.plastic.PlasticLookAndFeel");
            //UIManager.setLookAndFeel("com.jtatto.plaf.acryl.AcrylLookAndFeel");

        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFormEmpleado().setVisible(true);
            }
        });
    }
    public void calcula () {
        Calendar calendario=new GregorianCalendar();
        Date fechaHoraActual=new Date();
        calendario.setTime(fechaHoraActual);
        ampm=calendario.get(Calendar.AM_PM)==Calendar.AM?"AM":"PM";
        
        if(ampm.equals("PM")){
            int h=calendario.get(Calendar.HOUR_OF_DAY)-12;
            hora=h>9?""+h:"0"+h;
        }else{
            hora=calendario.get(Calendar.HOUR_OF_DAY)>9?""+calendario.get(Calendar.HOUR_OF_DAY):"0"+calendario.get(Calendar.HOUR_OF_DAY);
        }
        minutos=calendario.get(Calendar.MINUTE)>9?""+calendario.get(Calendar.MINUTE):"0"+calendario.get(Calendar.MINUTE);
        segundos=calendario.get(Calendar.SECOND)>9?""+calendario.get(Calendar.SECOND):"0"+calendario.get(Calendar.SECOND);
    }
    public void fecha(){
        Date fecha=new Date();
        //DateFormat dfDefault = DateFormat.getDateInstance();
        //DateFormat dfDateInstance = DateFormat.getDateInstance();
        DateFormat dfDateFull = DateFormat.getDateInstance(DateFormat.FULL);
        lblFecha.setText(dfDateFull.format(fecha).toUpperCase());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnControl;
    private javax.swing.JButton btnIngreso;
    private javax.swing.JButton btnOperarios;
    private javax.swing.JButton btnPago;
    private javax.swing.JButton btnPropietario;
    private javax.swing.JButton btnVehiculos;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane jpaneEscritorio;
    private javax.swing.JPanel jpaneMenu;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JLabel lblComentario;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFotoUser;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenu menuConf;
    private javax.swing.JMenuItem menuCuenta;
    private javax.swing.JMenu menuDiseño;
    private javax.swing.JMenuItem menuDiseño1;
    private javax.swing.JMenuItem menuDiseño2;
    private javax.swing.JMenuItem menuDiseño3;
    private javax.swing.JMenuItem menuDiseño4;
    private javax.swing.JMenu menuFondo;
    private javax.swing.JMenuItem menuFondo1;
    private javax.swing.JMenuItem menuFondo2;
    private javax.swing.JMenuItem menuFondo3;
    private javax.swing.JMenuItem menuFondo4;
    private javax.swing.JMenuItem menuFondo5;
    private javax.swing.JMenuItem menuFondo6;
    private javax.swing.JMenu menuInfo;
    private javax.swing.JMenu menuInicio;
    private javax.swing.JMenu menuSalir;
    // End of variables declaration//GEN-END:variables
    public class ImagenFondo implements Border {
        BufferedImage fondo;
        public ImagenFondo (String urls){
            try {
                //se obtine la imagen
                URL url = new URL(getClass().getResource(urls).toString());
                fondo=ImageIO.read(url);
            } catch(IOException ex) {
                Logger.getLogger(ImagenFondo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        //sobreescribir metodos de border
        @Override
        public void paintBorder(Component c, Graphics g, int x, int y, int width, int height) {
           g.drawImage(fondo, (x+(width-fondo.getWidth())/2), (y+(height-fondo.getHeight())/2), null);
        }

        @Override
        public Insets getBorderInsets(Component c) {
            return new Insets(0,0,0,0);
        }

        @Override
        public boolean isBorderOpaque() {
            return true;
        }
    }
}
