/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Frames.Administrador.MainFormAdministrador;
import Frames.Cliente.MainFormCliente;
import Frames.Empleado.MainFormEmpleado;
import java.io.IOException;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.border.TitledBorder;

/**
 *
 * @author Franklin
 */
public class Log extends javax.swing.JFrame {
    static Connection conn=null;
    static Statement st=null;
    public static ResultSet rs=null;
    public static int dni,transporte;
    /**
     * Creates new form Log
     */
    public Log() {
        initComponents();
        setBounds(0,0,1177, 600);
        setLocationRelativeTo(null);
        setResizable(false);
        setIconImage(new ImageIcon(getClass().getResource("/Icons/icon.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblPass1 = new javax.swing.JLabel();
        lblDni2 = new javax.swing.JLabel();
        lblPass3 = new javax.swing.JLabel();
        lblPass2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtDniR = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblDni1 = new javax.swing.JLabel();
        txtContraseñaR = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        txtCel = new javax.swing.JTextField();
        combUserR = new javax.swing.JComboBox<>();
        lblTipoTrans1 = new javax.swing.JLabel();
        combTransR = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();
        chkTerminosR = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        txtTransR = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblInicia = new javax.swing.JLabel();
        lblTipoUser = new javax.swing.JLabel();
        combUser = new javax.swing.JComboBox<>();
        lblFotoUser = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        lblDni = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JPasswordField();
        txtDni = new javax.swing.JTextField();
        chkTerminos = new javax.swing.JCheckBox();
        btnIniciar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblImgEmpresa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de transporte integrado: La solución para el Perú");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });

        jLabel3.setText("¿Aún no te registraste? Registrate en un click! Es gratis!     Registrar:");

        lblPass1.setText("Nombre:");

        lblDni2.setText("Apellido:");

        lblPass3.setText("Contraseña:");

        lblPass2.setText("Email:");

        lblDni1.setText("Ingrse DNI:");

        jLabel1.setText("Número de cel:");

        combUserR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Empleado", "Administrador" }));
        combUserR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combUserRActionPerformed(evt);
            }
        });

        lblTipoTrans1.setText("Tipo de transporte:");

        combTransR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Moto ", "Taxi", "Combi" }));

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/adduser.png"))); // NOI18N
        btnAgregar.setText("Registrarse");
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });

        chkTerminosR.setText("Acepto los terminos y condiciones");

        jLabel2.setText("ID transporte:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(combUserR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPass1)
                            .addComponent(lblDni2)
                            .addComponent(lblPass3)
                            .addComponent(lblPass2)
                            .addComponent(lblDni1))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnAgregar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDniR, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtContraseñaR, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(lblTipoTrans1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(combTransR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(chkTerminosR)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(93, 93, 93)
                                        .addComponent(txtTransR)))))))
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(combUserR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPass1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDni2)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipoTrans1)
                    .addComponent(combTransR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDniR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDni1)
                    .addComponent(jLabel2)
                    .addComponent(txtTransR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPass2)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkTerminosR))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPass3)
                    .addComponent(txtContraseñaR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregar)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
        });

        lblInicia.setText("Inicia sesión:");

        lblTipoUser.setText("Tipo de usuario:");

        combUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Empleado", "Administrador" }));
        combUser.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combUserItemStateChanged(evt);
            }
        });
        combUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combUserActionPerformed(evt);
            }
        });

        lblFotoUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/user.png"))); // NOI18N

        lblPass.setText("Contraseña:");

        lblDni.setText("DNI:");

        chkTerminos.setText("Acepto los terminos y condiciones");

        btnIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/send.png"))); // NOI18N
        btnIniciar.setText("Iniciar sesión");
        btnIniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIniciarMouseClicked(evt);
            }
        });
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblFotoUser)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPass)
                                    .addComponent(lblDni))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblInicia))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblTipoUser)
                                .addGap(18, 18, 18)
                                .addComponent(combUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(chkTerminos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                                .addComponent(btnIniciar)))
                        .addGap(37, 37, 37))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(lblInicia)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoUser)
                    .addComponent(combUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblFotoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDni)
                            .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPass)
                            .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIniciar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chkTerminos, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18))
        );

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblImgEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/empresa.jpg"))); // NOI18N
        lblImgEmpresa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblImgEmpresa.setMaximumSize(new java.awt.Dimension(50, 40));
        lblImgEmpresa.setMinimumSize(new java.awt.Dimension(52, 40));
        lblImgEmpresa.setPreferredSize(new java.awt.Dimension(50, 40));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImgEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lblImgEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combUserActionPerformed
        // TODO add your handling code here:
        /*String usuario="";
        usuario=(String)combUser.getSelectedItem();*/
    }//GEN-LAST:event_combUserActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // TODO add your handling code here:
        boolean bandera=false;
        String estado="",tipo="";
        boolean chk=chkTerminos.isSelected();
        
        try {
            int dni1=Integer.parseInt(txtDni.getText());
            String pass=getMD5(String.valueOf(txtContraseña.getPassword()));
            String usuario="",transporte1="";
            
            if(!chk==true)
                JOptionPane.showMessageDialog(null, "Acepte los terminos y condiciones");
            
            conn=App.ConnectionBd.Enlace(conn);
            String sql1="Select usuaUsua,EstaUsua,tipoUsua,Transporte_idTran from Usuario where usuaUsua='"
                    +dni1+"' and paswUsua='"+pass+"';";
            
            Statement st1=conn.createStatement();
            ResultSet rs1=st1.executeQuery(sql1);
            
            while(rs1.next()) {
                usuario=(String)rs1.getString(1);
                estado=(String)rs1.getString(2);
                tipo=(String)rs1.getString(3);
                transporte1=(String)rs1.getString(4);
            }
            
            bandera=true;
            dni=Integer.parseInt(usuario);
            transporte=Integer.parseInt(transporte1);
            conn.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al buscar datos, verifique los datos porfavor");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Introduzca los datos correctamente");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Introduzca los datos correctamente");
        }
        
        if(combUser.getSelectedItem().equals("Administrador")&&bandera==true&&chk==true&&estado.equals("Habilitado")&&combUser.getSelectedItem().equals(tipo)){
            MainFormAdministrador admi=new MainFormAdministrador();
            admi.setVisible(true);
            admi.setExtendedState(MAXIMIZED_BOTH);
            this.dispose();
        
        } else if(combUser.getSelectedItem().equals("Cliente")&& bandera==true&&chk==true&&estado.equals("Habilitado")&&combUser.getSelectedItem().equals(tipo)){
            MainFormCliente c=new MainFormCliente();
            c.setVisible(true);
            c.setExtendedState(MAXIMIZED_BOTH);
            this.dispose();
        
        } else if(combUser.getSelectedItem().equals("Empleado")&& bandera==true&&chk==true&&estado.equals("Habilitado")&&combUser.getSelectedItem().equals(tipo)){
            MainFormEmpleado e=new MainFormEmpleado();
            e.setVisible(true);
            e.setExtendedState(MAXIMIZED_BOTH);
            this.dispose();
        
        }
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnIniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarMouseClicked
        // TODO add your handling code here:
        /*if(combUser.getSelectedItem().equals("Administrador")){
            MainFormAdministrador admi=new MainFormAdministrador();
            admi.setVisible(true);
            admi.setExtendedState(MAXIMIZED_BOTH);
            this.dispose();
        
        } else if(combUser.getSelectedItem().equals("Cliente")){
            MainFormCliente c=new MainFormCliente();
            c.setVisible(true);
            c.setExtendedState(MAXIMIZED_BOTH);
            this.dispose();
        
        } else if(combUser.getSelectedItem().equals("Empleado")){
            MainFormEmpleado e=new MainFormEmpleado();
            e.setVisible(true);
            e.setExtendedState(MAXIMIZED_BOTH);
            this.dispose();
        
        }*/
    }//GEN-LAST:event_btnIniciarMouseClicked

    private void combUserItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combUserItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_combUserItemStateChanged

    private void combUserRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combUserRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combUserRActionPerformed

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        // TODO add your handling code here:
        boolean chk=chkTerminosR.isSelected();
        try {
            conn=App.ConnectionBd.Enlace(conn);
            st=App.ConnectionBd.sta(st);
            
            String nombre,apellido,celular,correo,banco,direccion,pass,tipo,estado,sSQL,ssSQL;
            //int dni,transporte;
            nombre=txtNombre.getText();
            apellido=txtApellido.getText();
            celular=txtCel.getText();
            correo=txtEmail.getText();
            banco="NULL";
            direccion="NULL";
            pass=getMD5(String.valueOf(txtContraseñaR.getPassword()));
            tipo=String.valueOf(combUserR.getSelectedItem());
            estado="Habilitado";
            dni=Integer.parseInt(txtDniR.getText());
            transporte=Integer.parseInt(txtTransR.getText());
            
            if (nombre.equals("")){
                JOptionPane.showMessageDialog(null, "Campos sin llenar");
                txtNombre.grabFocus();
            } else {
                
                if (combUserR.getSelectedItem()=="Administrador"&&chk == true) {
                    sSQL="insert into Usuario (Transporte_idTran,usuaUsua,paswUsua,tipoUsua,EstaUsua) values ('"
                            +transporte+"','"+dni+"','"+pass+"','"+tipo+"','"+estado+"');";
                    try{
                        Statement st=(Statement) conn.createStatement();
                        st.executeUpdate(sSQL);
                    } catch (SQLException ex){
                        JOptionPane.showMessageDialog(null, "Introduzca los datos correctamente");
                    }
                    
                    ssSQL="insert into Administrador (dniAdmi,nombAdmi,apelAdmi,celuAdmi,coreAdmi,cuenBancAdmi,"
                            + "direAdmi,Usuario_idUsua,Usuario_Transporte_idTran)values ('"+dni+"','"+nombre+"','"
                            +apellido+"','"+celular+"','"+correo+"','"+banco+"','"+direccion+"','"+dni+"','"+transporte+"');";
                    try{
                        Statement st=(Statement) conn.createStatement();
                        st.executeUpdate(ssSQL);
                        JOptionPane.showMessageDialog(null, "Registro exitoso");
                    } catch (SQLException ex){
                        JOptionPane.showMessageDialog(null, "Introduzca los datos correctamente");
                    }
                    //JOptionPane.showMessageDialog(null, "Registro exitoso");
                }
                if (combUserR.getSelectedItem()=="Empleado"&&chk == true) {
                    sSQL="insert into Usuario (Transporte_idTran,usuaUsua,paswUsua,tipoUsua,EstaUsua) values ('"
                            +transporte+"','"+dni+"','"+pass+"','"+tipo+"','"+estado+"');";
                    try{
                        Statement st=(Statement) conn.createStatement();
                        st.executeUpdate(sSQL);
                    } catch (SQLException ex){
                        JOptionPane.showMessageDialog(null, "Introduzca los datos correctamente");
                    }
                    ssSQL="insert into Empleado (dniEmpl,nombEmpl,apelEmpl,celuEmpl,coreEmpl,cuenBancEmpl,"
                            + "direEmpl,Usuario_idUsua,Usuario_Transporte_idTran)values ('"+dni+"','"+nombre+"','"
                            +apellido+"','"+celular+"','"+correo+"','"+banco+"','"+direccion+"','"+dni+"','"+transporte+"');";
                    try{
                        Statement st=(Statement) conn.createStatement();
                        st.executeUpdate(ssSQL);
                        JOptionPane.showMessageDialog(null, "Registro exitoso");
                    } catch (SQLException ex){
                        JOptionPane.showMessageDialog(null, "Introduzca los datos correctamente");
                    }
                    //JOptionPane.showMessageDialog(null, "Registro exitoso");
                }
                if (combUserR.getSelectedItem()=="Cliente"&&chk == true) {
                    sSQL="insert into Usuario (Transporte_idTran,usuaUsua,paswUsua,tipoUsua,EstaUsua) values ('"
                            +transporte+"','"+dni+"','"+pass+"','"+tipo+"','"+estado+"');";
                    try{
                        Statement st=(Statement) conn.createStatement();
                        st.executeUpdate(sSQL);
                    } catch (SQLException ex){
                        JOptionPane.showMessageDialog(null, "Introduzca los datos correctamente");
                    }
                    ssSQL="insert into Cliente (dniClie,nombClie,apelClie,celuClie,coreClie,cuenBancClie,"
                            + "direClie,Usuario_idUsua,Usuario_Transporte_idTran)values ('"+dni+"','"+nombre+"','"
                            +apellido+"','"+celular+"','"+correo+"','"+banco+"','"+direccion+"','"+dni+"','"+transporte+"');";
                    try{
                        Statement st=(Statement) conn.createStatement();
                        st.executeUpdate(ssSQL);
                        JOptionPane.showMessageDialog(null, "Registro exitoso");
                    } catch (SQLException ex){
                        JOptionPane.showMessageDialog(null, "Introduzca los datos correctamente");
                    }
                    //JOptionPane.showMessageDialog(null, "Registro exitoso");
                }
                
                if(!chk==true){
                    JOptionPane.showMessageDialog(null, "Acepte los terminos y condiciones");
                } else {
                    limpia();
                }
                //buscar("");
                conn.close();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al insertar el dato, verifique porfavor.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Introduzca los datos correctamente");
        }
    }//GEN-LAST:event_btnAgregarMouseClicked

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
        // TODO add your handling code here:
        jPanel2.setBorder(null);
        jPanel1.setBorder(jPanel3.getBorder());
    }//GEN-LAST:event_jPanel2MouseEntered

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        // TODO add your handling code here:
        jPanel1.setBorder(null);
        jPanel2.setBorder(jPanel3.getBorder());
    }//GEN-LAST:event_jPanel1MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        try {
            //Plantillas
            //UIManager.setLookAndFeel("com.sun.java.swing.plaf.metal.nimbus.NimbusLookAndFeel");
            //UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
            //UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.Windows.LookAndFeel");
            UIManager.setLookAndFeel("com.birosoft.liquid.LiquidLookAndFeel");
            //UIManager.setLookAndFeel("UpperEssential.UpperEssentialLookAndFeel");
            //UIManager.setLookAndFeel("com.jgoodies.looks.windows.WindowsLookAndFeel");
            //Plastic3DLookAndFeel.setPlasticTheme(new DarkStar());
            //UIManager.setLookAndFeel("com.jgoodies.looks.plastic.PlasticLookAndFeel");
            //UIManager.setLookAndFeel("com.jtatto.plaf.acryl.AcrylLookAndFeel");

        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }       
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Log().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JCheckBox chkTerminos;
    private javax.swing.JCheckBox chkTerminosR;
    private javax.swing.JComboBox<String> combTransR;
    private javax.swing.JComboBox<String> combUser;
    private javax.swing.JComboBox<String> combUserR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblDni1;
    private javax.swing.JLabel lblDni2;
    private javax.swing.JLabel lblFotoUser;
    private javax.swing.JLabel lblImgEmpresa;
    private javax.swing.JLabel lblInicia;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblPass1;
    private javax.swing.JLabel lblPass2;
    private javax.swing.JLabel lblPass3;
    private javax.swing.JLabel lblTipoTrans1;
    private javax.swing.JLabel lblTipoUser;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCel;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JPasswordField txtContraseñaR;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtDniR;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTransR;
    // End of variables declaration//GEN-END:variables
    private void limpia(){
        txtNombre.setText("");
        txtApellido.setText("");
        txtCel.setText("");
        txtEmail.setText("");
        txtContraseñaR.setText("");
        combUserR.setSelectedItem("");
        txtDniR.setText("");
        txtTransR.setText("");
        combUserR.setSelectedItem("Cliente");
        combTransR.setSelectedItem("Moto");
        txtNombre.grabFocus();
        btnAgregar.setText("Guardar");
    }
    
    //Encriptado
    public static String getMD5(String input) {
        try {
        MessageDigest md = MessageDigest.getInstance("MD5");
        byte[] messageDigest = md.digest(input.getBytes());
        BigInteger number = new BigInteger(1, messageDigest);
        String hashtext = number.toString(16);

        while (hashtext.length() < 32) {
        hashtext = "0" + hashtext;
        }
        return hashtext;
        }
        catch (NoSuchAlgorithmException e) {
        throw new RuntimeException(e);
        }
    }
}
