/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames.Cliente;

import Frames.Cuenta;
import Frames.Informacion;
import Frames.Log;
import com.jgoodies.looks.plastic.Plastic3DLookAndFeel;
import com.jgoodies.looks.plastic.theme.DarkStar;
import java.awt.Component;
import java.awt.Dimension;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Graphics;
import java.awt.Insets;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URL;
import java.text.DateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.border.Border;

/**
 *
 * @author Franklin
 */
public class MainFormCliente extends javax.swing.JFrame implements Runnable{
    Thread h1;
    String hora,minutos,segundos,ampm;
    Calendar calendario;
    String urls="/Icons/fondoEmpresa.png";
    @Override
    public void run(){
        Thread ct=Thread.currentThread();
        while(ct == h1){
            calcula();
            lblHora.setText(hora+ ":" + minutos+ ":" +segundos+" "+ampm);
            try {
                Thread.sleep(1000);
            } catch(InterruptedException e){}
        }
    }
    /**
     * Creates new form MainForm
     */
    public MainFormCliente() {
        initComponents();
        h1 = new Thread(this);
        h1.start();
        fecha();
        this.setExtendedState(MAXIMIZED_BOTH);
        setIconImage(new ImageIcon(getClass().getResource("/Icons/icon.png")).getImage());
        urls="/Icons/fondoEmpresa.png";
        paneEscritorio.setBorder(new ImagenFondo(urls));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblBienvenido = new javax.swing.JLabel();
        btnConsultas = new javax.swing.JButton();
        btnReserva = new javax.swing.JButton();
        lblFotoUser = new javax.swing.JLabel();
        btnAnular = new javax.swing.JButton();
        lblComentario = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        paneEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuInicio = new javax.swing.JMenu();
        menuConfig = new javax.swing.JMenu();
        menuCuenta = new javax.swing.JMenuItem();
        menuFondo = new javax.swing.JMenu();
        menuFondo1 = new javax.swing.JMenuItem();
        menuFondo2 = new javax.swing.JMenuItem();
        menuFondo3 = new javax.swing.JMenuItem();
        menuFondo4 = new javax.swing.JMenuItem();
        menuFondo5 = new javax.swing.JMenuItem();
        menuFondo6 = new javax.swing.JMenuItem();
        menuDiseño = new javax.swing.JMenu();
        menuDiseño1 = new javax.swing.JMenuItem();
        menuDiseño2 = new javax.swing.JMenuItem();
        menuDiseño3 = new javax.swing.JMenuItem();
        menuDiseño4 = new javax.swing.JMenuItem();
        menuInfo = new javax.swing.JMenu();
        menuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cliente - Sistema de transporte integrado: La solución para el Perú");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        lblBienvenido.setText("Bienvenido:");

        btnConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ConsultaCliente.png"))); // NOI18N
        btnConsultas.setText("Consultas de clientes");
        btnConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultasActionPerformed(evt);
            }
        });

        btnReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/reserva.png"))); // NOI18N
        btnReserva.setText("Generar reserva");
        btnReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservaActionPerformed(evt);
            }
        });

        lblFotoUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/user.png"))); // NOI18N

        btnAnular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/anular.png"))); // NOI18N
        btnAnular.setText("Anular reserva");
        btnAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblFotoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnConsultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblBienvenido)
                                    .addComponent(btnReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(btnAnular, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblFotoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBienvenido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReserva)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAnular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultas)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        lblComentario.setText("@stransintgr.com");

        lblFecha.setText("jLabel1");

        lblHora.setText("jLabel1");

        javax.swing.GroupLayout paneEscritorioLayout = new javax.swing.GroupLayout(paneEscritorio);
        paneEscritorio.setLayout(paneEscritorioLayout);
        paneEscritorioLayout.setHorizontalGroup(
            paneEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        paneEscritorioLayout.setVerticalGroup(
            paneEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        menuInicio.setText("Inicio");
        jMenuBar1.add(menuInicio);

        menuConfig.setText("Configuración");

        menuCuenta.setText("Cuenta");
        menuCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCuentaMouseClicked(evt);
            }
        });
        menuCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCuentaActionPerformed(evt);
            }
        });
        menuConfig.add(menuCuenta);

        menuFondo.setText("Fondo");

        menuFondo1.setText("Fondo 1");
        menuFondo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFondo1ActionPerformed(evt);
            }
        });
        menuFondo.add(menuFondo1);

        menuFondo2.setText("Fondo 2");
        menuFondo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFondo2ActionPerformed(evt);
            }
        });
        menuFondo.add(menuFondo2);

        menuFondo3.setText("Fondo 3");
        menuFondo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFondo3ActionPerformed(evt);
            }
        });
        menuFondo.add(menuFondo3);

        menuFondo4.setText("Fondo 4");
        menuFondo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFondo4ActionPerformed(evt);
            }
        });
        menuFondo.add(menuFondo4);

        menuFondo5.setText("Fondo 5");
        menuFondo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFondo5ActionPerformed(evt);
            }
        });
        menuFondo.add(menuFondo5);

        menuFondo6.setText("Fondo 6");
        menuFondo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFondo6ActionPerformed(evt);
            }
        });
        menuFondo.add(menuFondo6);

        menuConfig.add(menuFondo);

        menuDiseño.setText("Diseño");

        menuDiseño1.setText("Diseño 1");
        menuDiseño1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDiseño1ActionPerformed(evt);
            }
        });
        menuDiseño.add(menuDiseño1);

        menuDiseño2.setText("Diseño 2");
        menuDiseño2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDiseño2ActionPerformed(evt);
            }
        });
        menuDiseño.add(menuDiseño2);

        menuDiseño3.setText("Diseño 3");
        menuDiseño3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDiseño3ActionPerformed(evt);
            }
        });
        menuDiseño.add(menuDiseño3);

        menuDiseño4.setText("Diseño 4");
        menuDiseño4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDiseño4ActionPerformed(evt);
            }
        });
        menuDiseño.add(menuDiseño4);

        menuConfig.add(menuDiseño);

        jMenuBar1.add(menuConfig);

        menuInfo.setText("Información");
        menuInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuInfoMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuInfo);

        menuSalir.setText("Salir");
        menuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSalirMouseClicked(evt);
            }
        });
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblHora)
                        .addGap(33, 33, 33)
                        .addComponent(lblFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 256, Short.MAX_VALUE)
                        .addComponent(lblUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblComentario)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paneEscritorio))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(paneEscritorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHora)
                    .addComponent(lblFecha)
                    .addComponent(lblComentario)
                    .addComponent(lblUsuario)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnularActionPerformed
        // TODO add your handling code here:
        AnularReserva a=new AnularReserva();
        paneEscritorio.add(a);
        Dimension pantalla=Toolkit.getDefaultToolkit().getScreenSize();
        Dimension ventana=a.getSize();
        a.setLocation((pantalla.width-ventana.width)/3, (pantalla.height-ventana.height)/5);
        a.setVisible(true);
    }//GEN-LAST:event_btnAnularActionPerformed

    private void btnReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservaActionPerformed
        // TODO add your handling code here:
        GenerarReserva r=new GenerarReserva();
        paneEscritorio.add(r);
        Dimension pantalla=Toolkit.getDefaultToolkit().getScreenSize();
        Dimension ventana=r.getSize();
        r.setLocation((pantalla.width-ventana.width)/3, (pantalla.height-ventana.height)/5);
        r.setVisible(true);
    }//GEN-LAST:event_btnReservaActionPerformed

    private void btnConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultasActionPerformed
        // TODO add your handling code here:
        ConsultaCliente c=new ConsultaCliente();
        paneEscritorio.add(c);
        Dimension pantalla=Toolkit.getDefaultToolkit().getScreenSize();
        Dimension ventana=c.getSize();
        c.setLocation((pantalla.width-ventana.width)/3, (pantalla.height-ventana.height)/5);
        c.setVisible(true);
    }//GEN-LAST:event_btnConsultasActionPerformed

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuSalirActionPerformed

    private void menuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSalirMouseClicked
        // TODO add your handling code here:
        Log login=new Log();
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_menuSalirMouseClicked

    private void menuInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuInfoMouseClicked
        // TODO add your handling code here:
        Informacion i=new Informacion();
        paneEscritorio.add(i);
        Dimension pantalla=Toolkit.getDefaultToolkit().getScreenSize();
        Dimension ventana=i.getSize();
        i.setLocation((pantalla.width-ventana.width)/3, (pantalla.height-ventana.height)/5);
        i.setVisible(true); 
    }//GEN-LAST:event_menuInfoMouseClicked

    private void menuCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCuentaMouseClicked
        // TODO add your handling code here: 
    }//GEN-LAST:event_menuCuentaMouseClicked

    private void menuCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCuentaActionPerformed
        // TODO add your handling code here:
        Cuenta c=new Cuenta();
        paneEscritorio.add(c);
        Dimension pantalla=Toolkit.getDefaultToolkit().getScreenSize();
        Dimension ventana=c.getSize();
        c.setLocation((pantalla.width-ventana.width)/3, (pantalla.height-ventana.height)/5);
        c.setVisible(true); 
    }//GEN-LAST:event_menuCuentaActionPerformed

    private void menuFondo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFondo1ActionPerformed
        // TODO add your handling code here:
        urls="/Icons/fondo.png";
        paneEscritorio.setBorder(new ImagenFondo(urls));
    }//GEN-LAST:event_menuFondo1ActionPerformed

    private void menuFondo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFondo2ActionPerformed
        // TODO add your handling code here:
        urls="/Icons/fondo2.jpeg";
        paneEscritorio.setBorder(new ImagenFondo(urls));
    }//GEN-LAST:event_menuFondo2ActionPerformed

    private void menuFondo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFondo3ActionPerformed
        // TODO add your handling code here:
        urls="/Icons/fondo3.jpeg";
        paneEscritorio.setBorder(new ImagenFondo(urls));
    }//GEN-LAST:event_menuFondo3ActionPerformed

    private void menuFondo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFondo4ActionPerformed
        // TODO add your handling code here:
        urls="/Icons/fondo4.jpg";
        paneEscritorio.setBorder(new ImagenFondo(urls));
    }//GEN-LAST:event_menuFondo4ActionPerformed

    private void menuFondo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFondo5ActionPerformed
        // TODO add your handling code here:
        urls="/Icons/fondo5.jpg";
        paneEscritorio.setBorder(new ImagenFondo(urls));
    }//GEN-LAST:event_menuFondo5ActionPerformed

    private void menuFondo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFondo6ActionPerformed
        // TODO add your handling code here:
        urls="/Icons/fondoEmpresa.png";
        paneEscritorio.setBorder(new ImagenFondo(urls));
    }//GEN-LAST:event_menuFondo6ActionPerformed

    private void menuDiseño1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDiseño1ActionPerformed
        // TODO add your handling code here:
        try {
            Plastic3DLookAndFeel.setPlasticTheme(new DarkStar());
            UIManager.setLookAndFeel("com.jgoodies.looks.plastic.PlasticLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null,"Vuelva a iniciar sesión para visualizar los cambios.");
    }//GEN-LAST:event_menuDiseño1ActionPerformed

    private void menuDiseño2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDiseño2ActionPerformed
        // TODO add your handling code here:
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null,"Vuelva a iniciar sesión para visualizar los cambios.");
    }//GEN-LAST:event_menuDiseño2ActionPerformed

    private void menuDiseño3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDiseño3ActionPerformed
        // TODO add your handling code here:
        try {
            UIManager.setLookAndFeel("UpperEssential.UpperEssentialLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null,"Vuelva a iniciar sesión para visualizar los cambios.");
    }//GEN-LAST:event_menuDiseño3ActionPerformed

    private void menuDiseño4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDiseño4ActionPerformed
        // TODO add your handling code here:
        try {
            UIManager.setLookAndFeel("com.birosoft.liquid.LiquidLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null,"Vuelva a iniciar sesión para visualizar los cambios.");
    }//GEN-LAST:event_menuDiseño4ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        try {
            //Plantillas
            //UIManager.setLookAndFeel("com.sun.java.swing.plaf.metal.nimbus.NimbusLookAndFeel");
            //UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
            //UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.Windows.LookAndFeel");
            UIManager.setLookAndFeel("com.birosoft.liquid.LiquidLookAndFeel");
            //UIManager.setLookAndFeel("UpperEssential.UpperEssentialLookAndFeel");
            //UIManager.setLookAndFeel("com.jgoodies.looks.windows.WindowsLookAndFeel");
            //Plastic3DLookAndFeel.setPlasticTheme(new DarkStar());
            //UIManager.setLookAndFeel("com.jgoodies.looks.plastic.PlasticLookAndFeel");
            //UIManager.setLookAndFeel("com.jtatto.plaf.acryl.AcrylLookAndFeel");

        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFormCliente().setVisible(true);
            }
        });
    }
    public void calcula () {
        Calendar calendario=new GregorianCalendar();
        Date fechaHoraActual=new Date();
        calendario.setTime(fechaHoraActual);
        ampm=calendario.get(Calendar.AM_PM)==Calendar.AM?"AM":"PM";
        
        if(ampm.equals("PM")){
            int h=calendario.get(Calendar.HOUR_OF_DAY)-12;
            hora=h>9?""+h:"0"+h;
        }else{
            hora=calendario.get(Calendar.HOUR_OF_DAY)>9?""+calendario.get(Calendar.HOUR_OF_DAY):"0"+calendario.get(Calendar.HOUR_OF_DAY);
        }
        minutos=calendario.get(Calendar.MINUTE)>9?""+calendario.get(Calendar.MINUTE):"0"+calendario.get(Calendar.MINUTE);
        segundos=calendario.get(Calendar.SECOND)>9?""+calendario.get(Calendar.SECOND):"0"+calendario.get(Calendar.SECOND);
    }
    public void fecha(){
        Date fecha=new Date();
        //DateFormat dfDefault = DateFormat.getDateInstance();
        //DateFormat dfDateInstance = DateFormat.getDateInstance();
        DateFormat dfDateFull = DateFormat.getDateInstance(DateFormat.FULL);
        lblFecha.setText(dfDateFull.format(fecha).toUpperCase());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnular;
    private javax.swing.JButton btnConsultas;
    private javax.swing.JButton btnReserva;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JLabel lblComentario;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFotoUser;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenu menuConfig;
    private javax.swing.JMenuItem menuCuenta;
    private javax.swing.JMenu menuDiseño;
    private javax.swing.JMenuItem menuDiseño1;
    private javax.swing.JMenuItem menuDiseño2;
    private javax.swing.JMenuItem menuDiseño3;
    private javax.swing.JMenuItem menuDiseño4;
    private javax.swing.JMenu menuFondo;
    private javax.swing.JMenuItem menuFondo1;
    private javax.swing.JMenuItem menuFondo2;
    private javax.swing.JMenuItem menuFondo3;
    private javax.swing.JMenuItem menuFondo4;
    private javax.swing.JMenuItem menuFondo5;
    private javax.swing.JMenuItem menuFondo6;
    private javax.swing.JMenu menuInfo;
    private javax.swing.JMenu menuInicio;
    private javax.swing.JMenu menuSalir;
    private javax.swing.JDesktopPane paneEscritorio;
    // End of variables declaration//GEN-END:variables
    
    public class ImagenFondo implements Border {
        BufferedImage fondo;
        public ImagenFondo (String urls){
            try {
                //se obtine la imagen
                URL url = new URL(getClass().getResource(urls).toString());
                fondo=ImageIO.read(url);
            } catch(IOException ex) {
                Logger.getLogger(ImagenFondo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        //sobreescribir metodos de border
        @Override
        public void paintBorder(Component c, Graphics g, int x, int y, int width, int height) {
           g.drawImage(fondo, (x+(width-fondo.getWidth())/2), (y+(height-fondo.getHeight())/2), null);
        }

        @Override
        public Insets getBorderInsets(Component c) {
            return new Insets(0,0,0,0);
        }

        @Override
        public boolean isBorderOpaque() {
            return true;
        }
    }
}

